name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 0 */3 * *"
  workflow_dispatch: 
jobs:
  update-readme:
    name: Update Readme with badges
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: "goncalo-teixeira.3c7a5896"
